version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: tour-crm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: tourcrm
      POSTGRES_PASSWORD: tourcrm123
      POSTGRES_DB: tour_crm
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tour-crm-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U tourcrm -d tour_crm']
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: tour-crm-adminer
    restart: unless-stopped
    ports:
      - '8081:8080'
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: 'nette'
    networks:
      - tour-crm-network
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    container_name: tour-crm-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - tour-crm-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  tour-crm-network:
    driver: bridge
