'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Sparkles, Clock, HeartHandshake } from 'lucide-react';

export default function PublicPortalLandingPage() {
  const params = useParams();
  const locale = params.locale as string;

  const features = [
    {
      icon: Sparkles,
      title: 'AI-Powered Planning',
      description: 'Get personalized itineraries generated by our advanced AI technology tailored to your preferences.',
    },
    {
      icon: Clock,
      title: 'Instant Results',
      description: 'Receive your customized travel plan within minutes, not days.',
    },
    {
      icon: HeartHandshake,
      title: 'Expert Support',
      description: 'Our travel experts review and enhance every itinerary to ensure the best experience.',
    },
  ];

  const steps = [
    {
      number: '1',
      title: 'Share Your Preferences',
      description: 'Tell us about your destination, dates, travelers, and preferences.',
    },
    {
      number: '2',
      title: 'Get Your Itinerary',
      description: 'Our AI generates a personalized day-by-day travel plan instantly.',
    },
    {
      number: '3',
      title: 'Book Your Trip',
      description: 'Review your itinerary and request booking when you\'re ready.',
    },
  ];

  return (
    <div>
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-purple-600 via-indigo-600 to-blue-600 text-white py-20">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto text-center">
            <h1 className="text-5xl font-bold mb-6">
              Your Perfect Journey Starts Here
            </h1>
            <p className="text-xl mb-8 text-purple-100">
              Let AI create a personalized travel itinerary just for you. Tell us your dreams, and we&apos;ll plan the adventure.
            </p>
            <Link href={`/${locale}/portal/request`}>
              <Button size="lg" className="bg-white text-purple-600 hover:bg-purple-50 text-lg px-8 py-6">
                <Sparkles className="h-5 w-5 mr-2" />
                Request Your Itinerary
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16 bg-white">
        <div className="container mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">Why Choose Our Travel Portal?</h2>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              Experience the future of travel planning with AI-powered personalization and expert guidance.
            </p>
          </div>
          <div className="grid md:grid-cols-3 gap-8 max-w-5xl mx-auto">
            {features.map((feature) => {
              const Icon = feature.icon;
              return (
                <Card key={feature.title} className="text-center hover:shadow-lg transition-shadow">
                  <CardHeader>
                    <div className="mx-auto mb-4 bg-purple-100 w-16 h-16 rounded-full flex items-center justify-center">
                      <Icon className="h-8 w-8 text-purple-600" />
                    </div>
                    <CardTitle className="text-xl">{feature.title}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-gray-600">{feature.description}</p>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="py-16 bg-gray-50">
        <div className="container mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">How It Works</h2>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              Three simple steps to your dream vacation
            </p>
          </div>
          <div className="grid md:grid-cols-3 gap-8 max-w-5xl mx-auto">
            {steps.map((step, index) => (
              <div key={step.number} className="relative">
                {index < steps.length - 1 && (
                  <div className="hidden md:block absolute top-12 left-1/2 w-full h-0.5 bg-purple-200" />
                )}
                <div className="relative bg-white rounded-lg p-6 shadow-md">
                  <div className="mx-auto mb-4 bg-purple-600 w-12 h-12 rounded-full flex items-center justify-center text-white text-xl font-bold">
                    {step.number}
                  </div>
                  <h3 className="text-xl font-semibold text-gray-900 mb-2 text-center">
                    {step.title}
                  </h3>
                  <p className="text-gray-600 text-center">{step.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 bg-gradient-to-r from-purple-600 to-indigo-600 text-white">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-3xl font-bold mb-4">Ready to Start Your Adventure?</h2>
          <p className="text-xl mb-8 text-purple-100 max-w-2xl mx-auto">
            Create your personalized travel itinerary in minutes. No commitment required.
          </p>
          <Link href={`/${locale}/portal/request`}>
            <Button size="lg" className="bg-white text-purple-600 hover:bg-purple-50 text-lg px-8 py-6">
              Get Started Now
            </Button>
          </Link>
        </div>
      </section>

      {/* Popular Destinations Preview */}
      <section className="py-16 bg-white">
        <div className="container mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">Popular Destinations</h2>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              Explore our most requested travel destinations
            </p>
          </div>
          <div className="grid md:grid-cols-4 gap-6 max-w-6xl mx-auto">
            {[
              { name: 'Istanbul', country: 'Turkey', image: '🕌' },
              { name: 'Cappadocia', country: 'Turkey', image: '🎈' },
              { name: 'Antalya', country: 'Turkey', image: '🏖️' },
              { name: 'Ephesus', country: 'Turkey', image: '🏛️' },
            ].map((destination) => (
              <Card key={destination.name} className="hover:shadow-lg transition-shadow overflow-hidden">
                <div className="h-32 bg-gradient-to-br from-purple-400 to-indigo-400 flex items-center justify-center text-6xl">
                  {destination.image}
                </div>
                <CardContent className="pt-4">
                  <h3 className="font-semibold text-lg text-gray-900">{destination.name}</h3>
                  <p className="text-sm text-gray-600">{destination.country}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
