name: Run Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: tourcrm
          POSTGRES_PASSWORD: tourcrm123
          POSTGRES_DB: tour_crm_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Prisma migrations
        run: |
          cd apps/api
          npx prisma migrate deploy
        env:
          DATABASE_URL: postgresql://tourcrm:tourcrm123@localhost:5432/tour_crm_test

      - name: Run E2E tests
        run: |
          cd apps/api
          npm run test:e2e:cov
        env:
          DATABASE_URL: postgresql://tourcrm:tourcrm123@localhost:5432/tour_crm_test
          NODE_ENV: test
          JWT_SECRET: test-jwt-secret-min-32-characters-long-for-ci
          JWT_REFRESH_SECRET: test-refresh-secret-min-32-characters-long-for-ci

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          file: apps/api/coverage-e2e/lcov.info
          flags: e2e
          name: e2e-coverage

      - name: Run unit tests (shared package)
        run: |
          cd packages/shared
          npm run test
        continue-on-error: true  # Don't fail CI on unit test failures (for now)

      - name: Test Summary
        if: always()
        run: |
          echo "## Test Results" >> $GITHUB_STEP_SUMMARY
          echo "✅ E2E Tests Completed" >> $GITHUB_STEP_SUMMARY
          echo "📊 Coverage report uploaded" >> $GITHUB_STEP_SUMMARY
